---
title: "NCAA2026Post5"
author: "Orly Olbum"
date:
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(dplyr)
library(tidyr)
library(lubridate)
library(plotly)
```

## Data Prep

```{r data load}
setwd("/Users/orly/Library/CloudStorage/OneDrive-Personal/Swim Stats/NCAA Swimming")
ncaa26records = read.csv("NCAA2026ChampsRecords.csv")
head(ncaa26records)
```

## Quick Stats - Bar Charts

Total records broken F/M
```{r}
# get the data
ncaa26records_sex = ncaa26records %>%
  group_by(Sex) %>%
  summarise(Records = n())
ncaa26records_sex
```

```{r}
# plot the data
ncaa26records_sex_plot = plot_ly(
  data = ncaa26records_sex,
  x = ~Records,
  y = ~Sex,
  type = 'bar',
  marker = list(color = '#014F86'),
  orientation = 'h',
  text = ~Records,
  textposition = 'inside',
  insidetextanchor = 'middle',
  textfont = list(
    color = 'white', size = 18
  )) %>%
  layout(
    title = list(text = "NCAA 2026 Records (All Types) by Sex",
                 font = list(size = 24),
                 y = .99),
    xaxis = list(title = list(text = "Records",
                              font = list(size = 20)),
    tickfont = list(size = 15)),
    yaxis = list(title = list(text = "Sex",
                              font = list(size = 20),
                              standoff = 10),
                 tickfont = list(size = 15))
)
ncaa26records_sex_plot
```

Total records broken F/M - by type
```{r}
ncaa26records_sex_type = ncaa26records %>%
  group_by(Sex, Record.Type) %>%
  summarise(Records = n())
ncaa26records_sex_type

# sort it
ncaa26records_sex_type_sorted = ncaa26records_sex_type %>%
  group_by(Record.Type) %>%
  mutate(Total_Count = sum(Records)) %>%
  ungroup() %>%
  mutate(Record.Type = reorder(Record.Type, Total_Count))
```

```{r}
ncaa26records_sex_type_plot = plot_ly(
  data = ncaa26records_sex_type_sorted,
  x = ~Records,
  y = ~Record.Type,
  type = 'bar',
  color = ~Sex,
  colors = c('M' = '#014F86', 'F' = '#28BB8E'), # just tell it which one you want!
  orientation = 'h',
  text = ~Records,
  textposition = 'inside',
  insidetextanchor = 'middle',
  textfont = list(
    color = 'white', size = 15
  )) %>%
  layout(
    barmode = 'stack',
    title = list(text = "NCAA 2026 Records by Record Type",
                 font = list(size = 24),
                 y = .99),
    xaxis = list(title = list(text = "Records",
                              font = list(size = 20)),
    tickfont = list(size = 15)),
    yaxis = list(title = list(text = "Record Type",
                              font = list(size = 20),
                              standoff = 10),
                 tickfont = list(size = 15))
)
ncaa26records_sex_type_plot
```

Total records broken F/M - by school
```{r}
ncaa26records_sex_school = ncaa26records %>%
  group_by(Sex, School) %>%
  summarise(Records = n())
ncaa26records_sex_school

# sorted
ncaa26records_sex_school_sorted = ncaa26records_sex_school %>%
  group_by(School) %>%
  mutate(Total_Count = sum(Records)) %>%
  ungroup() %>%
  mutate(School = reorder(School, Total_Count))
```

```{r}
ncaa26records_sex_school_plot = plot_ly(
  data = ncaa26records_sex_school_sorted,
  x = ~Records,
  y = ~School,
  type = 'bar',
  color = ~Sex,
  colors = c('M' = '#0284C7', 'F' = '#E5E4E5'), # just tell it which one you want!
  orientation = 'h',
  text = ~Records,
  textposition = 'inside',
  insidetextanchor = 'middle',
  textfont = list(
    color = 'black', size = 15
  )) %>%
  layout(
    barmode = 'stack',
    title = list(text = "NCAA 2026 Records by School",
                 font = list(size = 24),
                 y = .99),
    xaxis = list(title = list(text = "Records",
                              font = list(size = 20)),
    tickfont = list(size = 15)),
    yaxis = list(title = list(text = "School",
                              font = list(size = 20),
                              standoff = 10),
                 tickfont = list(size = 15))
)
ncaa26records_sex_school_plot
```





